name: Create Airflow Docker images

on:
  push:
    paths:
      - 'plugins/airflow/docker/**'
      - '.github/workflows/airflow-docker.yml'

jobs:
  validate:
    name: Create Airflow Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        airflow-version: [1.10.2, 1.10.3, 1.10.6, 1.10.9]
        include:
          - airflow-version: 1.10.2
            airflow-extras: 'gcp_api,postgres'
          - airflow-version: 1.10.3
            airflow-extras: 'gcp_api,postgres'
          - airflow-version: 1.10.6
            airflow-extras: 'gcp,postgres'
          - airflow-version: 1.10.9
            airflow-extras: 'gcp,postgres'

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Docker build
        env:
          AIRFLOW_VERSION: ${{ matrix.airflow-version }}
          AIRFLOW_EXTRAS: ${{ matrix.airflow-extras }}
        run: cd plugins/airflow/docker && make build

      - name: Docker login
        if: github.ref == 'refs/heads/master'
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Docker push
        if: github.ref == 'refs/heads/master'
        env:
          AIRFLOW_TAG: ${{ matrix.airflow-version }}
        run: make push